version: '3'

volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}

services:
    react:
      build: ./pwa_cc
      image: pwa_cultural
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /data/certs:/etc/nginx/certs