# Generated by Django 3.1.4 on 2020-12-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('name', models.CharField(max_length=80)),
                ('icon', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('name', models.CharField(max_length=120)),
                ('principal_image', models.ImageField(upload_to='')),
                ('name_monitor', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity_persons', models.IntegerField()),
                ('required_materials', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_workshop', to='workshops.category')),
            ],
            options={
                'verbose_name_plural': 'Workshops',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=320)),
                ('image', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('workshops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops_materials', to='workshops.workshops')),
            ],
            options={
                'verbose_name_plural': 'Materials',
            },
        ),
    ]
