# Generated by Django 3.1.4 on 2020-12-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20201228_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
