# Generated by Django 3.1.4 on 2021-01-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_news', '0002_auto_20201228_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='principal_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
